'use strict';

const { processenv } = require('processenv');

const versions = require('./versions-autogenerated.json');

const configuration = {
  baseUrl: processenv('BASE_URL') || 'http://localhost:3000',
  title: processenv('TITLE') || 'wolkenkit Documentation',
  versions
};

module.exports = configuration;
